import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    POSTGRES_URL: z.string().min(1),
    POSTGRES_URL_NON_POOLING: z.string().min(1),
    POSTGRES_USER: z.string().min(1),
    POSTGRES_HOST: z.string().min(1),
    POSTGRES_PASSWORD: z.string().min(1),
    POSTGRES_DATABASE: z.string().min(1),
    POSTGRES_URL_NO_SSL: z.string().min(1),
    POSTGRES_PRISMA_URL: z.string().min(1),
    CLERK_SECRET_KEY: z.string().min(1),
    // GOOGLE_CLIENT_ID: z.string().min(1),
    // GOOGLE_CLIENT_SECRET: z.string().min(1),
    // DISCORD_CLIENT_ID: z.string().min(1),
    // DISCORD_CLIENT_SECRET: z.string().min(1),
    // DISCORD_TOKEN: z.string().min(1),
    // DISCORD_PUBLICK_KEY: z.string().min(1),
    // NOTION_API_SECRET: z.string().min(1),
    // NOTION_CLIENT_ID: z.string().min(1),
    // SLACK_SIGNING_SECRET: z.string().min(1),
    // SLACK_BOT_TOKEN: z.string().min(1),
    // SLACK_APP_TOKEN: z.string().min(1),
    // SLACK_CLIENT_ID: z.string().min(1),
    // SLACK_CLIENT_SECRET: z.string().min(1),
    // NOTION_REDIRECT_URI: z.string().min(1).url(),
    // SLACK_REDIRECT_URI: z.string().min(1).url(),
  },
  client: {
    NEXT_PUBLIC_URL: z.string().min(1).url(),
    NEXT_PUBLIC_DOMAIN: z.string().min(1),
    NEXT_PUBLIC_SCHEME: z.string().min(1),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().min(1),
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: z.string().min(1),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: z.string().min(1),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: z.string().min(1),
    // NEXT_PUBLIC_GOOGLE_SCOPES: z.string().min(1).url(),
    // NEXT_PUBLIC_OAUTH2_ENDPOINT: z.string().min(1).url(),
    NEXT_PUBLIC_DISCORD_REDIRECT: z.string().min(1).url(),
    NEXT_PUBLIC_NOTION_AUTH_URL: z.string().min(1).url(),
    NEXT_PUBLIC_SLACK_REDIRECT: z.string().min(1).url(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
    NEXT_PUBLIC_DOMAIN: process.env.NEXT_PUBLIC_DOMAIN,
    NEXT_PUBLIC_SCHEME: process.env.NEXT_PUBLIC_SCHEME,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL:
      process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL:
      process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
    // NEXT_PUBLIC_GOOGLE_SCOPES: process.env.NEXT_PUBLIC_GOOGLE_SCOPES,
    // NEXT_PUBLIC_OAUTH2_ENDPOINT: process.env.NEXT_PUBLIC_OAUTH2_ENDPOINT,
    NEXT_PUBLIC_DISCORD_REDIRECT: process.env.NEXT_PUBLIC_DISCORD_REDIRECT,
    NEXT_PUBLIC_NOTION_AUTH_URL: process.env.NEXT_PUBLIC_NOTION_AUTH_URL,
    NEXT_PUBLIC_SLACK_REDIRECT: process.env.NEXT_PUBLIC_SLACK_REDIRECT,
  },
})
